-- Watchtower schema. Apply once in the Supabase SQL editor.
-- Separate Supabase project recommended (independent failure domain).

-- 1. Every check attempt, append-only.
create table if not exists public.checks (
  id           bigint generated by default as identity primary key,
  slug         text not null,
  status       text not null check (status in ('ok','degraded','down','unconfigured')),
  http_status  int,
  latency_ms   int,
  checks       jsonb not null default '{}'::jsonb,
  version      text,
  error        text,
  checked_at   timestamptz not null default now()
);
create index if not exists checks_slug_checked_at_idx on public.checks (slug, checked_at desc);

-- 2. Latest status per project (fast lookup for alerts + dashboard).
create table if not exists public.current_status (
  slug             text primary key,
  status           text not null,
  last_checked_at  timestamptz not null default now(),
  last_latency_ms  int,
  last_error       text
);

-- 3. Frontend error reports (from window.onerror posts).
create table if not exists public.errors (
  id              bigint generated by default as identity primary key,
  slug            text,
  fingerprint     text not null,
  message         text not null,
  stack           text,
  url             text,
  user_agent      text,
  user_id         text,
  count           int not null default 1,
  first_seen_at   timestamptz not null default now(),
  last_seen_at    timestamptz not null default now()
);
create unique index if not exists errors_fingerprint_slug_idx on public.errors (fingerprint, slug);
create index if not exists errors_last_seen_idx on public.errors (last_seen_at desc);

-- 4. Rollup: uptime % and incident count per slug over rolling windows.
create or replace function public.uptime_summary()
returns table (
  slug text,
  uptime_24h numeric,
  uptime_7d numeric,
  uptime_30d numeric,
  incidents_7d int
)
language sql
as $$
  with recent as (
    select slug, status, checked_at
    from public.checks
    where checked_at > now() - interval '30 days'
  ),
  per_slug as (
    select
      slug,
      round(100.0 * sum(case when status = 'ok' and checked_at > now() - interval '24 hours' then 1 else 0 end)
            / nullif(sum(case when checked_at > now() - interval '24 hours' then 1 else 0 end), 0), 2) as uptime_24h,
      round(100.0 * sum(case when status = 'ok' and checked_at > now() - interval '7 days' then 1 else 0 end)
            / nullif(sum(case when checked_at > now() - interval '7 days' then 1 else 0 end), 0), 2) as uptime_7d,
      round(100.0 * sum(case when status = 'ok' then 1 else 0 end)
            / nullif(count(*), 0), 2) as uptime_30d
    from recent
    group by slug
  ),
  transitions as (
    -- Count ok -> not-ok transitions in the last 7 days.
    select
      slug,
      count(*) filter (
        where prev_status = 'ok'
          and status in ('down','degraded')
          and checked_at > now() - interval '7 days'
      ) as incidents_7d
    from (
      select
        slug, status, checked_at,
        lag(status) over (partition by slug order by checked_at) as prev_status
      from public.checks
      where checked_at > now() - interval '8 days'
    ) t
    group by slug
  )
  select
    p.slug,
    p.uptime_24h, p.uptime_7d, p.uptime_30d,
    coalesce(t.incidents_7d, 0)::int
  from per_slug p
  left join transitions t using (slug);
$$;

-- 5. RLS: checks/current_status readable by anon for dashboard; errors write-only via service role.
alter table public.checks          enable row level security;
alter table public.current_status  enable row level security;
alter table public.errors          enable row level security;

-- anon can read (dashboard is public-to-you-only because repo is private, but no secrets here)
drop policy if exists "anon read checks" on public.checks;
create policy "anon read checks" on public.checks for select using (true);
drop policy if exists "anon read current_status" on public.current_status;
create policy "anon read current_status" on public.current_status for select using (true);

-- errors are write-only from the edge function (service role bypasses RLS anyway)
drop policy if exists "anon read errors" on public.errors;
create policy "anon read errors" on public.errors for select using (true);
